# Generated by Django 4.0.4 on 2023-05-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_donor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='phone',
        ),
    ]
